CQRS/Models/ErrorViewModel.cs
namespace CQRS.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CQRS/Models/ListOfSchool.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace CQRS.Models
{
    public partial class ListOfSchool
    {
        public int Id { get; set; }
        [DisplayName("School Name")]
        public string SchooName { get; set; } = null!;
        public string Region { get; set; } = null!;
        [DisplayName("Schoo Number")]
        public string SchooNumber { get; set; } = null!;
        [DisplayName("School Type")]
        public string SchoolType { get; set; } = null!;
    }
}

CQRS/Controllers/HomeController.cs
using System.Diagnostics;
using CQRS.Models;
using Microsoft.AspNetCore.Mvc;

namespace CQRS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CQRS/Controllers/SchoolsController.cs
using CQRS.Features.Schools.Commands;
using CQRS.Features.Schools.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace CQRS.Controllers
{
    public class SchoolsController : Controller
    {
        private readonly IMediator _mediator;
        public SchoolsController(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _mediator.Send(new GetAllSchoolsQuery()));
        }

        
        public async Task<IActionResult> Details(int id)
        {
            return View(await _mediator.Send(new GetSchoolByIdQuery() { Id = id }));
        }

        
        // Get Create
        public IActionResult Create()
        {
            return View();
        }
        // Post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateSchoolCommand command)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _mediator.Send(command);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to save changes.");
            }
            return View(command);
        }

        // Get Edit
        public async Task<IActionResult> Edit(int id)
        {
            return View(await _mediator.Send(new GetSchoolByIdQuery() { Id = id }));
        }

        // Post Edit 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, UpdateSchoolCommand command)
        {
            if (id != command.Id)
            {
                return BadRequest();
            }

            try
            {
                if (ModelState.IsValid)
                {
                    await _mediator.Send(command);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to save changes.");
            }
            return View(command);
        }

        // Get Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _mediator.Send(new DeleteSchoolCommand() { Id = id });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to delete. ");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CQRS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CQRS/Views/Schools/Create.cshtml
@model CQRS.Models.ListOfSchool

@{
    ViewData["Title"] = "Create";
}


<h4>Add New School</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="SchooName" class="control-label"></label>
                <input asp-for="SchooName" class="form-control" />
                <span asp-validation-for="SchooName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SchooNumber" class="control-label"></label>
                <input asp-for="SchooNumber" class="form-control" />
                <span asp-validation-for="SchooNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SchoolType" class="control-label"></label>
                <input asp-for="SchoolType" class="form-control" />
                <span asp-validation-for="SchoolType" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CQRS/Views/Schools/Delete.cshtml
@model CQRS.Models.ListOfSchool

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ListOfSchool</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SchooName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SchooName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SchooNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SchooNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SchoolType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SchoolType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CQRS/Views/Schools/Details.cshtml
@model CQRS.Models.ListOfSchool

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>School Information</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SchooName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SchooName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SchooNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SchooNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SchoolType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SchoolType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a> |
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

CQRS/Views/Schools/Edit.cshtml
@model CQRS.Models.ListOfSchool

@{
    ViewData["Title"] = "Edit";
}


<h4>Edit School Info</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SchooName" class="control-label"></label>
                <input asp-for="SchooName" class="form-control" />
                <span asp-validation-for="SchooName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SchooNumber" class="control-label"></label>
                <input asp-for="SchooNumber" class="form-control" />
                <span asp-validation-for="SchooNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SchoolType" class="control-label"></label>
                <input asp-for="SchoolType" class="form-control" />
                <span asp-validation-for="SchoolType" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                 <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

@*<div>
    

             <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CQRS/Views/Schools/Index.cshtml
@model IEnumerable<CQRS.Models.ListOfSchool>

@{
    ViewData["Title"] = "Schools in The Gambia";
}

<h1>Schools in The Gambia</h1>

<p>
    <a asp-controller="Schools" asp-action="Create"  class="btn btn-success">Create New</a>
</p>
@*<div class="row">
    <div class="col">
        <h1>Players</h1>
    </div>
    <div class="col text-right">
        <a asp-controller="Schools" asp-action="Create" class="btn btn-success">Create New</a>
    </div>
</div>*@

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SchooName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SchooNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SchoolType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SchooName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SchooNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SchoolType)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CQRS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CQRS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CQRS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CQRS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Schools" asp-action="Index">Schools</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CQRS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>